from django.contrib import admin

from inventario.models import *

admin.site.register(Bodega)
admin.site.register(Producto)
admin.site.register(SubProducto)
admin.site.register(DetalleSubProducto)
admin.site.register(ProductoBodega)
admin.site.register(SubProductoBodega)
admin.site.register(Cargo)
admin.site.register(Cliente)
admin.site.register(Empleado)
admin.site.register(Venta)
admin.site.register(DetalleVenta)
admin.site.register(Traslado)
admin.site.register(DetalleTraslado)
admin.site.register(Proveedor)
admin.site.register(Compra)
admin.site.register(Ganado)
admin.site.register(DetalleCompra)
admin.site.register(Canal)
admin.site.register(PlanillaDesposte)
admin.site.register(DesposteCanal)
admin.site.register(DetallePlanilla)
admin.site.register(Enlagunado)
admin.site.register(DetalleEnlagunado)
admin.site.register(LimpezaTajado)
admin.site.register(Formula)
admin.site.register(DetalleFormula)
admin.site.register(Condimentado)
admin.site.register(Miga)
admin.site.register(DetalleMiga)
admin.site.register(Apanado)
